### PR TITLE
(WIP) fix #33 Add sticky sidebar for content pages

### PR DESCRIPTION
**Pull request by kahboom**
Fixes #33, possibly addresses #37, #38 and #40 but haven't really been able to test that. :/ The footer is not sticking to the bottom on empty pages, but that fix literally requires a couple of lines of code, but it's late so I'll do that in the morning. If you'd like, just wait for me and I'll push up those changes first thing.

## Screenshots

screenshot 2017-05-18 21 33 06

screenshot 2017-05-18 21 33 20

@jimmidyson Do you want me to start squashing some of these commits? :joy:

Live demo: https://kahboom.github.io/syndesis.io/

### CODE REVIEW

**Comment by jimmidyson** [comment]
Let's squash commits when we decide to merge.

This is looking great!

Here's a couple of issues when offcanvas though:

1. Scrolls up over navbar, looks a bit rubbish:
image

2. Goes to single line when phone sized narrow:
image

**Comment by kahboom** [comment]
Fixed sticky footer and now sticky sidebar begins to detach from footer on short pages. This does not happen on full pages, so could possibly need to adjust content height -- this should be happening automatically but isn't. Need to investigate further. See below for screenshots.

## Sticky sidebar & footer on long pages

screenshot 2017-05-19 15 49 10


## Sticky sidebar & footer on short pages

screenshot 2017-05-19 15 47 57

**Comment by kahboom** [comment]
Fixed the issue with the sticky sidebar and sticky footer. Checked across all device sizes. See screenshots below.

## Smaller Devices

screenshot 2017-05-19 21 41 18 screenshot 2017-05-19 21 41 32
screenshot 2017-05-19 21 40 58


## Small-Medium Devices

screenshot 2017-05-19 21 17 50

##  Tablets

screenshot 2017-05-19 21 40 47

screenshot 2017-05-19 20 52 01





## Desktops

screenshot 2017-05-19 21 40 05

screenshot 2017-05-19 15 49 10


Also fixed the overflow issue below on smaller devices:

screenshot 2017-05-19 20 08 27 screenshot 2017-05-19 22 23 26


---

cc @jimmidyson 

That should cover most, if not all, of the content pages on all those devices. Only a few problems now on the home page. It now slides left/right slightly and it is driving me nuts. Thankfully it's not much, but I need to fix it. On mobile (possibly even desktop) the footer doesn't take up the whole width, so if you scroll to the right its white, but the top takes up the whole width (hence the scrolling/slide-y issue). Phew.. I'll take a look at that when I get the chance. Need a break for now.

Let me know if you'd rather merge now and we fix that later. Since it's on the homepage it may be best to wait?

**Comment by kahboom** [comment]
Oh the tablet screenshot was outdated; I removed that annoying outline that is added to buttons on focus:

screenshot 2017-05-19 22 30 47

**Comment by jimmidyson** [comment]
So there is no more offcanvas sidebar any more on narrower screens?

One problem as well:
image

**Comment by kahboom** [comment]
@jimmidyson Which is the off-canvas sidebar? The TOC? I am not sure where it went, but I can add it back in again. What was the resolution for that screenshot? The sidenav should have taken up the whole width at that point.

**Comment by jimmidyson** [comment]
See the current site how side nav is currently off canvas style.

No idea on resolution, sorry! Just try to make your window wider/narrower a bit. Can find out later if need be.

**Comment by kahboom** [comment]
@jimmidyson I'll add that back in with a burger icon (I hated that show/hide text button) and try to replicate that screen size for the second issue - I made sure to test with all the device sizes available on Chrome Dev Tools, so not sure what happened. I'll check again by just resizing my browser screen as well.

**Comment by kahboom** [comment]
cc @jimmidyson  - Nearly there, see demo video [here](https://www.useloom.com/share/15ca772470624946b89b14b3517f8042).

And some screen shots of the small resolution (video is much more helpful):

001-sm
002-sm
003-sm004-sm


Resolved:
~1. Sticky footer.~
~2. Sticky sidebar.~
~3. Special sticky toggle-able sub-menu for sub nav and TOC on mobile devices.~
~4. Cross-device compatibility (with a few caveats, listed below).~

Stickiness required restructuring some of the layout, which lead to outstanding issue 3 below.

Outstanding issues:
1. Merge conflicts!
2. TOC is hidden for tablets.
3. Center content area overflows horizontally.  This does not currently happen on the staging site atm, but that's also because I adjusted the layout structure. I think this structure is better from a technical standpoint, but it means I need to adjust the center content area. Note that the nav bars and footer do not have this overflow issue.
4. Sub-menu for mobile (with sidenav and TOC toggles) should be replaced with font icons and styled more.
5. Make TOC sticky for large and extra large devices, like the sidenav.
6. Minor padding issue with sub-nav menu (kind of visible in screenshots above).

Only no. 1 and 2 are major showstoppers, and I'll fix that within a few minutes. The others should not prevent this PR from being merged.

**Comment by kahboom** [comment]
#BiggestPROfAllTime

**Comment by kahboom** [comment]
Also, the overflow problem is only one the home page - or at least, does not occur on the Quick Start page.

**Pull request closed without merging**
